### ISSUE TITLE
tokenize() in quanteda changed

### ISSUE THREAD

**Issue by lecy** [kasperwelbers/semnet#2]
It looks like the `quanteda` package has updated some functions, and `tokenize()` has changed to `tokens()`. Looks like it is breaking your code:

```
library(semnet)
text = c('Renewable fuel is better than fossil fuels!',
           'A fueled debate about fuel',
           'Mark_Rutte is simply Rutte')
tokens = asTokenlist(text)
tokens

Error in asTokenlist(text) : 
  Tokenlist argument should be one of the following:
- tokenizedTexts class (quanteda)
- corpus class (quanteda)
- tokenlist class (semnet)
- a data.frame with document_id, position and word columns (see the *.col arguments)
- a character vector

```

**Comment by kasperwelbers** [comment]
Cool, thanks for the heads up! I'll fix it in a minute.

As a sidenote, semnet is not really being developed anymore (but I'll maintain it in case of bugs like these), since most of the functionalities are built into the corpustools package that we're working on.

**Comment by lecy** [comment]
Good to know! I'll check it out. Thanks.
